### ISSUE TITLE
App architecture

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#871]
We're in a place reminiscent of the articles app around August - we have a build up months of quick hacks, prototypes and tests and now we're approaching a time where we really need to get this stuff specced and more stable.

@callumlocke Did some good work last week towards making our main streams controller more readable  and easier to reason about by lessening the tangle of promises.

@andygnewman Has done some very handy work in how we configure streams of different types which will become increasingly useful.

However we still have a nest of conditionals attaching features. It's not fun to work with!

So, can we discuss how we can better architect this app to make it easier to reason about and much easier to test.

**My idea** is that streams could act a more like streams. We're all familiar with Gulp - input gets passed through filters and transforms then the output is gathered, and I think we could do something similar. 

Features should be standalone modules (mostly the case) and appended to the set of transformations based on the stream config. They'll probably need to implement two methods: the first to modify the request and a second to modify the data sent to the template. Both should return a promise for control flow but whether or not they return a value or modify the given reference is up for debate.

I think this would make for a thin, easily testable controller and each add-on can be reasoned about and tested in isolation. Hardly a conditional in sight.

Anyway, thoughts?

CC master builder @matthew-andrews

**Comment by matthew-andrews** [comment]
I like it.  Would each transform need to block before passing to the next one?

**Comment by i-like-robots** [comment]
_Ideally_ no because each add-on would run in isolation and only be concerned with its business. In reality I'm sure there will be cases where this is not true and concerns are crossed. 100% agree simple and slower > complex and fast.

**Comment by i-like-robots** [comment]
I just pushed a concept of this for fast FT and plugins for tag filters and the article model:

Controller:
https://github.com/Financial-Times/next-stream-page/blob/c4da4699c74ae221aeafd331e9c2c8d3463de169/server/controllers/fast-ft.js

Transform plugin for filters:
https://github.com/Financial-Times/next-stream-page/blob/c4da4699c74ae221aeafd331e9c2c8d3463de169/server/controllers/transforms/filter-by.js

This has been complicated a little by maintaining some backwards compatibility but nothing that wouldn't be easy to clean up.

**Comment by callumlocke** [comment]
I like this a lot.

Could we have a little readme in each transform's directory to say what it does?

**Comment by callumlocke** [comment]
Wondering if a transform should export a single function that *returns* the transformer object with `in` and `out` methods? Some transforms may need to be configured per-stream. 

Also, the order of transforms for a given stream does matter, because multiple transforms might insert extra rows at specified indexes in the `items` array, so these insertions should always be done in the same order to be predictable.

I'm picturing config looking something like this:

```js
// server/config/streams.json
{
  "MQ==-U2VjdGlvbnM=": {
    "name": "World",
    "transforms": [
      "live",
      "open-in-stream",
      ["branded", {"classExtension": "fastft"}], // a transform with args
    ]
  },
  // ...etc
}
```

```js
// server/config/transforms.json
{
  "live": {"liveStreams": true}} // flag requirements for the 'live' transform
}
```

explanation:

- `streams.json` – for enabling transforms per-stream

- `transforms.json` – for restricting transforms to certain flag combinations

- the `stream-config.js` module's job is to check both config files, and return a config object that includes a `transforms` array of ready-to-use transform objects

- you could still hack in `stream-config.js` if you need to hackily add/remove a transform based on some criteria other than flags/streamId

**Comment by matthew-andrews** [comment]
I'd suggest making them `.js` files rather than `.json` files, then in the `transforms` section you could pass a reference to **actual** transform function:-

e.g.

```
const live = require('./transforms/live');
const openInStream = require('./transforms/live');

module.exports = {
  // World
  "MQ==-U2VjdGlvbnM=": {
    transforms: [
      live,
      openInStream,
      branded({ classExtension: "fastft" }) // a transform with args (curried(?) function)
    ]
  },
  // ...etc
};
```

May I also suggest we get away from storing the name as a property and as a comment instead…  It's only there to help us know what the random base64 IDs refer to but will potentially be confusing as editorial are able to rename them at any time.  (UK's EU Referendum was, only a short while ago, EU Referendum.  It isn't unlikely to change again)

**Comment by matthew-andrews** [comment]
[ Justification for the first point: we built something similar for the web app — each section defined as JSON — but it turned into a nightmare as we started implementing **programming language** features (such as inheritance) *in JSON*.  Given in your first example you're already started to do the same (arguments) I think just using JavaScript is simply and eliminates the need for code to interpret the JSON ]

**Comment by callumlocke** [comment]
:+1: totally agree

Except I think **all** plugins should have the same API, for consistency – i.e. they all export a single function, which returns an `{in, out}` object.

so

```js
module.exports = {
  // World
  "MQ==-U2VjdGlvbnM=": {
    transforms: [
      live(),
      openInStream(),
      branded({ classExtension: "fastft" })
    ]
  },
  // ...etc
};
```

**Comment by matthew-andrews** [comment]
that's a nice improvement, yep :+1:

**Comment by i-like-robots** [comment]
Sounds good. I'll continue with my branch and get the FastFT filters out of the door. We can talk about implementing the updated configuration early next week maybe?

**Comment by i-like-robots** [comment]
Realised `in` is a bad name as it's also a keyword. Would input/output be better or pre/post?

**Comment by andygnewman** [comment]
My vote wold be for pre / post as it implies there is a core process happening in the middle.

**Comment by i-like-robots** [comment]
Here's an example of the current setup, the profile for the FastFT stream:

```
	{
		name: 'FastFT',
		match: (req) => {
			const ids = [
				'5c7592a8-1f0c-11e4-b0cb-b2227cce2b54',
				'NTlhNzEyMzMtZjBjZi00Y2U1LTg0ODUtZWVjNmEyYmU1NzQ2-QnJhbmRz'
			];

			return ids.indexOf(req.params.thingId) > -1;
		},
		transforms: [
			filterBy(),
			articleModel()
		]
	}
```

There are some properties that are boolean (E.G. `isLive`) and suited to the kind of configuration we have now. Should these be handled via transforms or as an options field within the profile?

**Comment by i-like-robots** [comment]
So we're looking good to go with the basic implementation in #879 so I guess we need to work out where to go next and how to migrate the existing add ons such as hot topics.

Also now would be a good time to make noise about any potential issues or poor decisions. I personally have some concerns about arbitrarily attaching extra properties onto the request/response objects, could this be improved?

**Comment by callumlocke** [comment]
> concerns about arbitrarily attaching extra properties onto the request/response objects

Do you mean for data shared between pre and post of a given transform? Maybe share a plain object as the context for both pre and post, so pre can just hang stuff on `this` and post can pick it up. One this object per transform per request. (I realised my thing of putting stuff in local vars in shared scope is broken because one 'instance' of a plugin is shared by all requests.) The problem with transforms putting arbitrary properties on the res/req is not only a bad smell, it actually doesn't work if you use the same transform twice in one profile (unless the transforms compute the property names in some way).

Also, small thing but I think flags should be passed in as a third argument to pre and post - it feels weird to look for them in res, especially from pre

**Comment by i-like-robots** [comment]
> I realised my idea of putting local vars in the shared scope of pre and post is broken because one 'instance' of a plugin is shared by all requests

Ahh, for some reason I was thinking we created a new profile instance per request but no. I think that's for the best. The idea of a `this` scope (A la Mocha) was something I considered but forgot about. We should do this!

> I think flags should be passed in as a third argument to pre and post

Agree

**Comment by i-like-robots** [comment]
https://github.com/Financial-Times/next-stream-page/wiki/Writing-a-stream-transform-plugin

**Comment by matthew-andrews** [comment]
\p/
