### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-stream-page#956]
We're repeatedly bumping into our memory limit in production.

![screen shot 2016-03-11 at 16 03 27](https://cloud.githubusercontent.com/assets/271645/13707713/d595ce40-e7a2-11e5-98eb-8679cd765adf.png)

**Comment by i-like-robots** [comment]
This looks to my untrained eye like a memory leak. Testing locally (pushing a roughly similar number of requests to various endpoints with [siege](https://github.com/JoeDog/siege)) it's clear that memory rises very quickly under load to ~1GB.

What makes me think this is a leak though is that when the siege is stopped the memory does not recover:

Starting memory (and loading 1 stream page): ~150mb
Memory long after siege has ended: ~550mb

**Comment by bjfletcher** [comment]
![image](https://cloud.githubusercontent.com/assets/733849/14497108/9a338748-018d-11e6-8ec6-b39213f18195.png)

The number of R14 (memory quota exceeded) has been reduced significantly, but not gone completely. About once every 15 minutes now, rather than about once every 30-60 second.

I see that the response times graph, about 30 minutes after startup, start to spike every about 5 minutes, presumably GC'ing.  The spikes are < 1 minute each.

Previously response time was between 400ms and 800ms, now between 300ms and 400ms.  Previously there were spikes seemingly to be because of some external factors of anywhere up to 3s.  The spikes I've mentioned above have response times of about 1s.  I'm yet to see any other kind of spikes as I've only been observing this for the last 1 hour.

Plan of action:

1. lower the limit from 490 MB to see if we can stop the memory exceeded quota completely;
2. investigate how to avoid the spikes - e.g., ask Node to use a different GC strategy.

**Comment by bjfletcher** [comment]
![image](https://cloud.githubusercontent.com/assets/733849/14498503/9f4da646-0192-11e6-9e0f-3fb17aafcf57.png)

Interestingly, the spikes have now stopped.  No spike in the last 45 minutes.

**Comment by bjfletcher** [comment]
Looks like we shouldn't worry about getting rid of the R14 errors completely, Heroku says:

> Using small amounts of swap space and infrequent memory swapping are usually not problems. Even when your application hasn’t reached its memory limit, it’s common to see small amounts of memory being swapped to disk as the operating system manages memory and available disk cache.

https://devcenter.heroku.com/articles/dynos#memory-behavior

> R14 - Memory quota exceeded
> A dyno requires memory in excess of its quota. If this error occurs, the dyno will page to swap space to continue running, which may cause degraded process performance. The R14 error is calculated by total memory swap and rss; cache is not included.

https://devcenter.heroku.com/articles/error-codes#r14-memory-quota-exceeded

So, let's try and reduce the limit slightly and see if the app alert "Memory quota exceeded. There have been n memory errors in the current time period" will go away. Presumably this alert happens only when the number of R14 errors go over a certain threshold.

**Comment by i-like-robots** [comment]
Sounds good, thanks for investigating!

**Comment by andygnewman** [comment]
Good approach to get node to fix the problem, but does it mask an underlying problem in our code (or a dependency somewhere) that is not managing itself properly? Is there a way to also diagnose this?

**Comment by matthew-andrews** [comment]
should we roll this out more widely?

**Comment by andygnewman** [comment]
@bjfletcher Can this issue be closed now?
